openapi: 3.0.0
info:
    title: Task Manager API
    description: A simple API to manage tasks.
    version: 1.0.0
servers:
    - url: http://localhost:5000
paths:
    /tasks:
        get:
            summary: Get all tasks
            description: Retrieves a list of all tasks in the system.
            responses:
                "200":
                    description: A list of tasks
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Task"
                "400":
                    description: A bad request( this shouldn't be the only error response)

        post:
            summary: Create a new task
            description: Adds a new task to the system.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NewTask"
            responses:
                "201":
                    description: The created task
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                "400":
                    description: Invalid request payload or missing title
    /tasks/{id}:
        get:
            summary: Get a task by ID
            description: Retrieves the details of a single task by its ID.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: The requested task
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                "404":
                    description: Task not found
        put:
            summary: Update a task by ID
            description: Updates the details of an existing task. You can provide one or more fields to update.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Task"
            responses:
                "200":
                    description: The updated task
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                "404":
                    description: Task not found
        delete:
            summary: Delete a task by ID
            description: Deletes a task from the system.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "204":
                    description: Task deleted successfully
                "404":
                    description: Task not found
components:
    schemas:
        Task:
            type: object
            properties:
                id:
                    type: string
                    readOnly: true
                title:
                    type: string
                description:
                    type: string
                due_date:
                    type: string
                    format: date-time
                status:
                    type: string
                    enum:
                        - Pending
                        - In Progress
                        - Completed
        NewTask:
            type: object
            properties:
                title:
                    type: string
                description:
                    type: string
                due_date:
                    type: string
                    format: date-time
                status:
                    type: string
                    enum:
                        - Pending
                        - In Progress
                        - Completed
