openapi: 3.0.0
info:
    title: Task Manager API
    description: A simple API to manage tasks.
    version: 1.0.0
servers:
    - url: http://localhost:5000
paths:
    /register:
        post:
            summary: Register a new user
            description: Creates a new user account.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NewUser"
            responses:
                "201":
                    description: User registered successfully
                "400":
                    description: Invalid request payload or username already exists
                "500":
                    description: Unexpected error

    /login:
        post:
            summary: Login
            description: Authenticates a user and returns a JWT token.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/LoginCredentials"
            responses:
                "200":
                    description: The JWT token
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string
                "400":
                    description: Invalid request payload
                "401":
                    description: Invalid credentials
                "500":
                    description: Unexpected error

    /api/promote/{id}:
        post:
            summary: Promote a user to admin
            description: Promotes a user to an admin role. This endpoint requires admin privileges.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: User promoted to admin successfully
                "400":
                    description: Invalid user ID format
                "401":
                    description: Unauthorized
                "404":
                    description: User not found
                "500":
                    description: Unexpected error

    /api/tasks:
        get:
            summary: Get all tasks
            description: Retrieves a list of all tasks in the system.
            responses:
                "200":
                    description: A list of tasks
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Task"
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized

        post:
            summary: Create a new task
            description: Adds a new task to the system.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NewTask"
            responses:
                "201":
                    description: The created task
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                "400":
                    description: Invalid request payload or missing title
                "401":
                    description: Unauthorized

    /api/tasks/{id}:
        get:
            summary: Get a task by ID
            description: Retrieves the details of a single task by its ID.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: The requested task
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                "401":
                    description: Unauthorized
                "404":
                    description: Task not found

        put:
            summary: Update a task by ID
            description: Updates the details of an existing task. You can provide one or more fields to update.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Task"
            responses:
                "200":
                    description: The updated task
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                "400":
                    description: Invalid request payload
                "401":
                    description: Unauthorized
                "404":
                    description: Task not found

        delete:
            summary: Delete a task by ID
            description: Deletes a task from the system.
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                "204":
                    description: Task deleted successfully
                "401":
                    description: Unauthorized
                "404":
                    description: Task not found

components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: string
                    readOnly: true
                username:
                    type: string
                role:
                    type: string
                    enum:
                        - admin
                        - user

        NewUser:
            type: object
            required:
                - username
                - password
            properties:
                username:
                    type: string
                password:
                    type: string

        LoginCredentials:
            type: object
            required:
                - username
                - password
            properties:
                username:
                    type: string
                password:
                    type: string

        Task:
            type: object
            properties:
                id:
                    type: string
                    readOnly: true
                title:
                    type: string
                description:
                    type: string
                due_date:
                    type: string
                    format: date-time
                status:
                    type: string
                    enum:
                        - Pending
                        - In Progress
                        - Completed

        NewTask:
            type: object
            required:
                - title
            properties:
                title:
                    type: string
                description:
                    type: string
                due_date:
                    type: string
                    format: date-time
                status:
                    type: string
                    enum:
                        - Pending
                        - In Progress
                        - Completed
